nameOverride: ""
fullnameOverride: ""
namespace: "dev"
replicaCount: 2

image:
  repository: nginxinc/nginx-unprivileged
  tag: "1.27-alpine"
  pullPolicy: IfNotPresent

imagePullSecrets: []

service:
  type: ClusterIP
  port: 8080
  targetPort: http

route:
  enabled: true
  host: "nginx.dev.ocptoaks.com"
  path: ""
  wildcardPolicy: None
  tls:
    enabled: true
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

containerPort: 8080

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: ""

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  storageClassName: "ocpsc"
  size: 1Gi
  mountPath: /usr/share/nginx/html
  annotations: {}

podAnnotations: {}
podLabels: {}

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  runAsNonRoot: true

nodeSelector: {}
tolerations: []
affinity: {}
