{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "nginx-ocp.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "nginx-ocp.labels" . | nindent 4 }}
spec:
  {{- with .Values.route.host }}
  host: {{ . | quote }}
  {{- end }}
  {{- with .Values.route.path }}
  path: {{ . | quote }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "nginx-ocp.fullname" . }}
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: {{ .Values.route.wildcardPolicy }}
  {{- if .Values.route.tls.enabled }}
  tls:
    termination: {{ .Values.route.tls.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.route.tls.insecureEdgeTerminationPolicy }}
  {{- end }}
{{- end }}
